classDiagram
    CartEntity "0..*" -- "0..*" SmartphoneEntity
    CartEntity "0..*" -- "0..*" LaptopEntity

    ProductItem <|-- Ticket
    ProductItem <|-- Publication
    Publication <|-- Book
    Publication <|-- Magazine
    Magazine <|-- DiscMag

    SaleableItem <|.. ProductItem
    Serializable <|.. ProductItem

    ProductItem <-- CashTill
    Cart "0..*" -- "0..*" ProductItem : contains

    ProductEntity <|-- SmartphoneEntity
    ProductEntity <|-- LaptopEntity

    class ProductEntity {
        <<abstract>>
    }

    class SmartphoneEntity {
        +String brand
        +int warrantyMonths
        +int storageGb
        +boolean has5g
    }

    class LaptopEntity {
        +String brand
        +int warrantyMonths
        +int ramGb
        +String cpuModel
    }

    class CartEntity
    class Cart {
        -Long id
    }

    class ProductItem {
        -String productId
    }

    class Serializable {
        <<interface>>
    }

    class Ticket {
        +String description
        +double price
        +sellItem()
    }

    class Publication {
        <<abstract>>
        -String title
        -double price
        -int copies
        +getPrice()

        +Publication()
        +Publication(String title, double price, int copies)
        +toString()
        +equals()
        +hashCode()
    }

    class Book {
        -String author
        +edit()
        +initialize()
        +sellItem()

        +Book()
        +Book(String author)
        +Book(String author, String title, double price, int copies)
        +toString()
        +equals()
        +hashCode()
    }

    class Magazine {
        -int orderQty
        -java.util.Date currentIssue

        +Magazine()
        +Magazine(int orderQty, java.util.Date currentIssue, String title, double price, int copies)

        +edit()
        +initialize()
        +sellItem()
    }

    class DiscMag {
        -boolean hasDisc
        +edit()
        +initialize()
        +sellItem()

        +DiscMag()
        +DiscMag(boolean hasDisc, int orderQty, java.util.Date currentIssue, String title, double price, int copies)
    }

    class CashTill {
        -double runningTotal
        +CashTill()
        +showTotal()
        +sellItem(SaleableItem item)
    }

    class SaleableItem {
        <<interface>>
        +sellItem()
        +getPrice()
    }
